DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status SMALLINT NOT NULL DEFAULT 0,
    priority SMALLINT NOT NULL DEFAULT 0,
    deadline TIMESTAMP,
    tags TEXT NOT NULL
);
